import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Dummy from '../components/dummy'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* This is styled-jsx */}
      <Dummy/>
      <style jsx>
        {`
        .mySpan{
          color: red;
        }
        `}
      </style>

      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingCoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href='/' passHref><li>Home</li></Link>
          <Link href='/about' passHref><li>About</li></Link>
          <Link href='/blog' passHref><li>Blogs</li></Link>
          <Link href='/contact' passHref><li>Contact</li></Link>
        </ul>
      </nav>

      <main className={styles.main}>

        <h1 className={styles.title}>
          <span className="mySpan dummy">Hunting Coders</span>
        </h1>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022 ?</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam reiciendis distinctio explicabo.</p>
          </div>

          <div className="blogItem">
            <h3>How to learn JavaScript in 2022 ?</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam reiciendis distinctio explicabo.</p>
          </div>

          <div className="blogItem">
            <h3>How to learn JavaScript in 2022 ?</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam reiciendis distinctio explicabo.</p>
          </div>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
